import { observable } from "mobx";

const obsSkills = observable({
  acrobatics: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  appraise: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  bluff: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  climb: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  craft: [],
  diplomacy: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  disableDevice: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  disguise: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  escapeArtist: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  fly: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  handleAnimal: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  heal: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  intimidate: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  knowledge: [],
  linguistics: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  perception: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  perform: [],
  profession: [],
  ride: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  senseMotive: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  sleightOfHand: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  spellcraft: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  stealth: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  survival: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  swim: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  useMagicDevice: {
    classSkill: { value: false, isHidden: true },
    name: { value: "", isHidden: true },
    description: { value: "", isHidden: true },
    total: { value: 0, isHidden: true },
    abilityModifierType: { value: "", isHidden: true },
    abilityModifier: { value: 0, isHidden: true },
    ranks: { value: 0, isHidden: true },
    class: { value: 0, isHidden: true },
    racial: { value: 0, isHidden: true },
    trait: { value: 0, isHidden: true },
    misc: { value: 0, isHidden: true }
  },
  conditionalModifiersAndOtherNotes: { value: "", isHidden: true },
  languages: { value: "", isHidden: true },
  experiencePoints: {
    total: { value: 0, isHidden: true },
    nextLevel: { value: 0, isHidden: true }
  }
});

export default obsSkills;
