import { observable } from "mobx";

const obsSkills = observable({
  acrobatics: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  appraise: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  bluff: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  climb: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  craft: [
    {
      classSkill: 0,
      name: "",
      description: "",
      total: 0,
      abilityModifierType: "",
      abilityModifier: 0,
      ranks: 0,
      class: 0,
      racial: 0,
      trait: 0,
      misc: 0
    }
  ],
  diplomacy: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  disableDevice: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  disguise: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  escapeArtist: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  fly: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  handleAnimal: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  heal: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  intimidate: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  knowledge: [
    {
      classSkill: 0,
      name: "",
      description: "",
      total: 0,
      abilityModifierType: "",
      abilityModifier: 0,
      ranks: 0,
      class: 0,
      racial: 0,
      trait: 0,
      misc: 0
    }
  ],
  linguistics: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  perception: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  perform: [
    {
      classSkill: 0,
      name: "",
      description: "",
      total: 0,
      abilityModifierType: "",
      abilityModifier: 0,
      ranks: 0,
      class: 0,
      racial: 0,
      trait: 0,
      misc: 0
    }
  ],
  profession: [
    {
      classSkill: 0,
      name: "",
      description: "",
      total: 0,
      abilityModifierType: "",
      abilityModifier: 0,
      ranks: 0,
      class: 0,
      racial: 0,
      trait: 0,
      misc: 0
    }
  ],
  ride: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  senseMotive: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  sleightOfHand: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  spellcraft: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  stealth: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  survival: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  swim: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  useMagicDevice: {
    classSkill: 0,
    name: "",
    description: "",
    total: 0,
    abilityModifierType: "",
    abilityModifier: 0,
    ranks: 0,
    class: 0,
    racial: 0,
    trait: 0,
    misc: 0
  },
  conditionalModifiersAndOtherNotes: "",
  languages: "",
  experiencePoints: {
    total: 0,
    nextLevel: 0
  }
});

export default obsSkills;
